spring:
  datasource:
    url: jdbc:mysql://localhost:3307/book_store?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082


app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 604800000